# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rXc0if9DnswRApyqk4EZ023sv7sMPXRA
"""

a = input()
b = a.split()
p = 0
for n in b:
  if int(n) < 60:
    p = p+1

print(p)